controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
cart_index:
        path: /cart
        controller: App\Controller\CartController::index
cart_add:
        path: /add/{id}
        controller: App\Controller\CartController::add
cart_remove:
        path: /cart/remove/{id}
        controller: App\Controller\CartController::remove
delete_all:
        path: /delete
        controller: App\Controller\CartController::deleteAll
app_contact:
        path: /contact
        controller: App\Controller\ContactController::contact
        methods: [GET, POST]
    
